@echo off
setlocal enabledelayedexpansion
set "version=Version 0.2 Beta by MurakumoJP"
title League of Legends Delete Language %version%
REM ----------------------------------------------------------
REM Menu selection
REM ----------------------------------------------------------
set exitoption=
echo   %version%
echo [---------------------------------]
echo [  Select the language to delete  ]
echo [---------------------------------]
echo [     [- ja_JP -]  [- ko_KR -]    ]
echo [     [- ru_RU -]  [- en_US -]    ]
echo [---------------------------------]
echo.
set /p option=.  Enter a language: 
echo.
echo ---------------------------------------------------------
echo.
if "%option%"=="ja_JP" goto language
if "%option%"=="ru_RU" goto language
if "%option%"=="ko_KR" goto language
if "%option%"=="en_US" goto language
goto init

:language
del "League of Legends\Game\DATA\FINAL\Champions\Aatrox.%option%.wad.client"
del "League of Legends\Game\DATA\FINAL\Champions\Ahri.%option%.wad.client"
del "League of Legends\Game\DATA\FINAL\Champions\Akali.%option%.wad.client"
del "League of Legends\Game\DATA\FINAL\Champions\Alistar.%option%.wad.client"
del "League of Legends\Game\DATA\FINAL\Champions\Amumu.%option%.wad.client"
del "League of Legends\Game\DATA\FINAL\Champions\Anivia.%option%.wad.client"
del "League of Legends\Game\DATA\FINAL\Champions\Annie.%option%.wad.client"
del "League of Legends\Game\DATA\FINAL\Champions\Ashe.%option%.wad.client"
del "League of Legends\Game\DATA\FINAL\Champions\AurelionSol.%option%.wad.client"
del "League of Legends\Game\DATA\FINAL\Champions\Azir.%option%.wad.client"
del "League of Legends\Game\DATA\FINAL\Champions\Bard.%option%.wad.client"
del "League of Legends\Game\DATA\FINAL\Champions\Blitzcrank.%option%.wad.client"
del "League of Legends\Game\DATA\FINAL\Champions\Brand.%option%.wad.client"
del "League of Legends\Game\DATA\FINAL\Champions\Braum.%option%.wad.client"
del "League of Legends\Game\DATA\FINAL\Champions\Caitlyn.%option%.wad.client"
del "League of Legends\Game\DATA\FINAL\Champions\Camille.%option%.wad.client"
del "League of Legends\Game\DATA\FINAL\Champions\Cassiopeia.%option%.wad.client"
del "League of Legends\Game\DATA\FINAL\Champions\Chogath.%option%.wad.client"
del "League of Legends\Game\DATA\FINAL\Champions\Corki.%option%.wad.client"
del "League of Legends\Game\DATA\FINAL\Champions\Darius.%option%.wad.client"
del "League of Legends\Game\DATA\FINAL\Champions\Diana.%option%.wad.client"
del "League of Legends\Game\DATA\FINAL\Champions\Draven.%option%.wad.client"
del "League of Legends\Game\DATA\FINAL\Champions\DrMundo.%option%.wad.client"
del "League of Legends\Game\DATA\FINAL\Champions\Ekko.%option%.wad.client"
del "League of Legends\Game\DATA\FINAL\Champions\Elise.%option%.wad.client"
del "League of Legends\Game\DATA\FINAL\Champions\Evelynn.%option%.wad.client"
del "League of Legends\Game\DATA\FINAL\Champions\Ezreal.%option%.wad.client"
del "League of Legends\Game\DATA\FINAL\Champions\FiddleSticks.%option%.wad.client"
del "League of Legends\Game\DATA\FINAL\Champions\Fiora.%option%.wad.client"
del "League of Legends\Game\DATA\FINAL\Champions\Fizz.%option%.wad.client"
del "League of Legends\Game\DATA\FINAL\Champions\Galio.%option%.wad.client"
del "League of Legends\Game\DATA\FINAL\Champions\Gangplank.%option%.wad.client"
del "League of Legends\Game\DATA\FINAL\Champions\Garen.%option%.wad.client"
del "League of Legends\Game\DATA\FINAL\Champions\Gnar.%option%.wad.client"
del "League of Legends\Game\DATA\FINAL\Champions\Gragas.%option%.wad.client"
del "League of Legends\Game\DATA\FINAL\Champions\Graves.%option%.wad.client"
del "League of Legends\Game\DATA\FINAL\Champions\Hecarim.%option%.wad.client"
del "League of Legends\Game\DATA\FINAL\Champions\Heimerdinger.%option%.wad.client"
del "League of Legends\Game\DATA\FINAL\Champions\Illaoi.%option%.wad.client"
del "League of Legends\Game\DATA\FINAL\Champions\Irelia.%option%.wad.client"
del "League of Legends\Game\DATA\FINAL\Champions\Ivern.%option%.wad.client"
del "League of Legends\Game\DATA\FINAL\Champions\Janna.%option%.wad.client"
del "League of Legends\Game\DATA\FINAL\Champions\JarvanIV.%option%.wad.client"
del "League of Legends\Game\DATA\FINAL\Champions\Jax.%option%.wad.client"
del "League of Legends\Game\DATA\FINAL\Champions\Jayce.%option%.wad.client"
del "League of Legends\Game\DATA\FINAL\Champions\Jhin.%option%.wad.client"
del "League of Legends\Game\DATA\FINAL\Champions\Jinx.%option%.wad.client"
del "League of Legends\Game\DATA\FINAL\Champions\Kaisa.%option%.wad.client"
del "League of Legends\Game\DATA\FINAL\Champions\Kalista.%option%.wad.client"
del "League of Legends\Game\DATA\FINAL\Champions\Karma.%option%.wad.client"
del "League of Legends\Game\DATA\FINAL\Champions\Karthus.%option%.wad.client"
del "League of Legends\Game\DATA\FINAL\Champions\Kassadin.%option%.wad.client"
del "League of Legends\Game\DATA\FINAL\Champions\Katarina.%option%.wad.client"
del "League of Legends\Game\DATA\FINAL\Champions\Kayle.%option%.wad.client"
del "League of Legends\Game\DATA\FINAL\Champions\Kayn.%option%.wad.client"
del "League of Legends\Game\DATA\FINAL\Champions\Kennen.%option%.wad.client"
del "League of Legends\Game\DATA\FINAL\Champions\Khazix.%option%.wad.client"
del "League of Legends\Game\DATA\FINAL\Champions\Kindred.%option%.wad.client"
del "League of Legends\Game\DATA\FINAL\Champions\Kled.%option%.wad.client"
del "League of Legends\Game\DATA\FINAL\Champions\KogMaw.%option%.wad.client"
del "League of Legends\Game\DATA\FINAL\Champions\Leblanc.%option%.wad.client"
del "League of Legends\Game\DATA\FINAL\Champions\LeeSin.%option%.wad.client"
del "League of Legends\Game\DATA\FINAL\Champions\Leona.%option%.wad.client"
del "League of Legends\Game\DATA\FINAL\Champions\Lissandra.%option%.wad.client"
del "League of Legends\Game\DATA\FINAL\Champions\Lucian.%option%.wad.client"
del "League of Legends\Game\DATA\FINAL\Champions\Lulu.%option%.wad.client"
del "League of Legends\Game\DATA\FINAL\Champions\Lux.%option%.wad.client"
del "League of Legends\Game\DATA\FINAL\Champions\Malphite.%option%.wad.client"
del "League of Legends\Game\DATA\FINAL\Champions\Malzahar.%option%.wad.client"
del "League of Legends\Game\DATA\FINAL\Champions\Maokai.%option%.wad.client"
del "League of Legends\Game\DATA\FINAL\Champions\MasterYi.%option%.wad.client"
del "League of Legends\Game\DATA\FINAL\Champions\MissFortune.%option%.wad.client"
del "League of Legends\Game\DATA\FINAL\Champions\MonkeyKing.%option%.wad.client"
del "League of Legends\Game\DATA\FINAL\Champions\Mordekaiser.%option%.wad.client"
del "League of Legends\Game\DATA\FINAL\Champions\Morgana.%option%.wad.client"
del "League of Legends\Game\DATA\FINAL\Champions\Nami.%option%.wad.client"
del "League of Legends\Game\DATA\FINAL\Champions\Nasus.%option%.wad.client"
del "League of Legends\Game\DATA\FINAL\Champions\Nautilus.%option%.wad.client"
del "League of Legends\Game\DATA\FINAL\Champions\Neeko.%option%.wad.client"
del "League of Legends\Game\DATA\FINAL\Champions\Nidalee.%option%.wad.client"
del "League of Legends\Game\DATA\FINAL\Champions\Nocturne.%option%.wad.client"
del "League of Legends\Game\DATA\FINAL\Champions\Nunu.%option%.wad.client"
del "League of Legends\Game\DATA\FINAL\Champions\Olaf.%option%.wad.client"
del "League of Legends\Game\DATA\FINAL\Champions\Orianna.%option%.wad.client"
del "League of Legends\Game\DATA\FINAL\Champions\Ornn.%option%.wad.client"
del "League of Legends\Game\DATA\FINAL\Champions\Pantheon.%option%.wad.client"
del "League of Legends\Game\DATA\FINAL\Champions\Poppy.%option%.wad.client"
del "League of Legends\Game\DATA\FINAL\Champions\Pyke.%option%.wad.client"
del "League of Legends\Game\DATA\FINAL\Champions\Qiyana.%option%.wad.client"
del "League of Legends\Game\DATA\FINAL\Champions\Quinn.%option%.wad.client"
del "League of Legends\Game\DATA\FINAL\Champions\Rakan.%option%.wad.client"
del "League of Legends\Game\DATA\FINAL\Champions\Rammus.%option%.wad.client"
del "League of Legends\Game\DATA\FINAL\Champions\RekSai.%option%.wad.client"
del "League of Legends\Game\DATA\FINAL\Champions\Renekton.%option%.wad.client"
del "League of Legends\Game\DATA\FINAL\Champions\Rengar.%option%.wad.client"
del "League of Legends\Game\DATA\FINAL\Champions\Riven.%option%.wad.client"
del "League of Legends\Game\DATA\FINAL\Champions\Rumble.%option%.wad.client"
del "League of Legends\Game\DATA\FINAL\Champions\Ryze.%option%.wad.client"
del "League of Legends\Game\DATA\FINAL\Champions\Sejuani.%option%.wad.client"
del "League of Legends\Game\DATA\FINAL\Champions\Senna.%option%.wad.client"
del "League of Legends\Game\DATA\FINAL\Champions\SG_ChoGath.%option%.wad.client"
del "League of Legends\Game\DATA\FINAL\Champions\SG_KhaZix.%option%.wad.client"
del "League of Legends\Game\DATA\FINAL\Champions\SG_KogMaw.%option%.wad.client"
del "League of Legends\Game\DATA\FINAL\Champions\SG_RekSai.%option%.wad.client"
del "League of Legends\Game\DATA\FINAL\Champions\SG_Skarner.%option%.wad.client"
del "League of Legends\Game\DATA\FINAL\Champions\SG_VelKoz.%option%.wad.client"
del "League of Legends\Game\DATA\FINAL\Champions\Shaco.%option%.wad.client"
del "League of Legends\Game\DATA\FINAL\Champions\Shen.%option%.wad.client"
del "League of Legends\Game\DATA\FINAL\Champions\Shyvana.%option%.wad.client"
del "League of Legends\Game\DATA\FINAL\Champions\Singed.%option%.wad.client"
del "League of Legends\Game\DATA\FINAL\Champions\Sion.%option%.wad.client"
del "League of Legends\Game\DATA\FINAL\Champions\Sivir.%option%.wad.client"
del "League of Legends\Game\DATA\FINAL\Champions\Skarner.%option%.wad.client"
del "League of Legends\Game\DATA\FINAL\Champions\Sona.%option%.wad.client"
del "League of Legends\Game\DATA\FINAL\Champions\Soraka.%option%.wad.client"
del "League of Legends\Game\DATA\FINAL\Champions\Swain.%option%.wad.client"
del "League of Legends\Game\DATA\FINAL\Champions\Sylas.%option%.wad.client"
del "League of Legends\Game\DATA\FINAL\Champions\Syndra.%option%.wad.client"
del "League of Legends\Game\DATA\FINAL\Champions\TahmKench.%option%.wad.client"
del "League of Legends\Game\DATA\FINAL\Champions\Taliyah.%option%.wad.client"
del "League of Legends\Game\DATA\FINAL\Champions\Talon.%option%.wad.client"
del "League of Legends\Game\DATA\FINAL\Champions\Taric.%option%.wad.client"
del "League of Legends\Game\DATA\FINAL\Champions\Teemo.%option%.wad.client"
del "League of Legends\Game\DATA\FINAL\Champions\TFTChampion.%option%.wad.client"
del "League of Legends\Game\DATA\FINAL\Champions\Thresh.%option%.wad.client"
del "League of Legends\Game\DATA\FINAL\Champions\Tristana.%option%.wad.client"
del "League of Legends\Game\DATA\FINAL\Champions\Trundle.%option%.wad.client"
del "League of Legends\Game\DATA\FINAL\Champions\Tryndamere.%option%.wad.client"
del "League of Legends\Game\DATA\FINAL\Champions\TwistedFate.%option%.wad.client"
del "League of Legends\Game\DATA\FINAL\Champions\Twitch.%option%.wad.client"
del "League of Legends\Game\DATA\FINAL\Champions\Udyr.%option%.wad.client"
del "League of Legends\Game\DATA\FINAL\Champions\Urgot.%option%.wad.client"
del "League of Legends\Game\DATA\FINAL\Champions\Varus.%option%.wad.client"
del "League of Legends\Game\DATA\FINAL\Champions\Vayne.%option%.wad.client"
del "League of Legends\Game\DATA\FINAL\Champions\Veigar.%option%.wad.client"
del "League of Legends\Game\DATA\FINAL\Champions\Velkoz.%option%.wad.client"
del "League of Legends\Game\DATA\FINAL\Champions\Vi.%option%.wad.client"
del "League of Legends\Game\DATA\FINAL\Champions\Viktor.%option%.wad.client"
del "League of Legends\Game\DATA\FINAL\Champions\Vladimir.%option%.wad.client"
del "League of Legends\Game\DATA\FINAL\Champions\Volibear.%option%.wad.client"
del "League of Legends\Game\DATA\FINAL\Champions\Warwick.%option%.wad.client"
del "League of Legends\Game\DATA\FINAL\Champions\Xayah.%option%.wad.client"
del "League of Legends\Game\DATA\FINAL\Champions\Xerath.%option%.wad.client"
del "League of Legends\Game\DATA\FINAL\Champions\XinZhao.%option%.wad.client"
del "League of Legends\Game\DATA\FINAL\Champions\Yasuo.%option%.wad.client"
del "League of Legends\Game\DATA\FINAL\Champions\Yorick.%option%.wad.client"
del "League of Legends\Game\DATA\FINAL\Champions\Yuumi.%option%.wad.client"
del "League of Legends\Game\DATA\FINAL\Champions\Zac.%option%.wad.client"
del "League of Legends\Game\DATA\FINAL\Champions\Zed.%option%.wad.client"
del "League of Legends\Game\DATA\FINAL\Champions\Ziggs.%option%.wad.client"
del "League of Legends\Game\DATA\FINAL\Champions\Zilean.%option%.wad.client"
del "League of Legends\Game\DATA\FINAL\Champions\Zoe.%option%.wad.client"
del "League of Legends\Game\DATA\FINAL\Champions\Zyra.%option%.wad.client"
del "League of Legends\Game\DATA\FINAL\Localized\Global.%option%.wad.client"
del "League of Legends\Game\DATA\FINAL\Maps\Shipping\Common.%option%.wad.client"
del "League of Legends\Game\DATA\FINAL\Maps\Shipping\Map10.%option%.wad.client"
del "League of Legends\Game\DATA\FINAL\Maps\Shipping\Map11.%option%.wad.client"
del "League of Legends\Game\DATA\FINAL\Maps\Shipping\Map12.%option%.wad.client"
del "League of Legends\Game\DATA\FINAL\Maps\Shipping\Map22.%option%.wad.client"
del "League of Legends\Game\DATA\FINAL\UI.%option%.wad.client"
cls
echo.
echo Deleting the %option% language is complete
pause